version: '3.8'

services:
  caderninho-api:
    image: 10.0.0.131:5001/caderninho-api:latest
    container_name: caderninho-api
    restart: unless-stopped
    ports:
      - "5000:8080"
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/caderninho.db
      - ASPNETCORE_URLS=http://+:8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - caderninho-network

networks:
  caderninho-network:
    driver: bridge

volumes:
  data:
    driver: local
